BrandBakuMVC/BrandShopMVC/BrandShopMVC/ViewComponents/FooterViewComponent.cs
using BrandShop.Business.DTOs.FooterDto;
using BrandShop.Business.DTOs.HeaderDto;
using BrandShop.Business.DTOs.ProductDto;
using BrandShop.Core.Entities;
using BrandShop.Data.DAL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BrandShopMVC.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public FooterViewComponent(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            FooterDto footerDto = new FooterDto
            {
                Brand = _context.Brands.ToList(),
            };
            return View(footerDto);
        }
    }
}

BrandBakuMVC/BrandShopMVC/BrandShopMVC/ViewComponents/HeaderViewComponent.cs
using BrandShop.Business.DTOs.HeaderDto;
using BrandShop.Business.DTOs.ProductDto;
using BrandShop.Core.Entities;
using BrandShop.Data.DAL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BrandShopMVC.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public HeaderViewComponent(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            BasketDto basket = null;

            AppUser user = null;

            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }


            if (user != null && user.IsAdmin == false)
            {
                basket = _getBasketItems(_context.BasketItems.Include(x => x.Product).ThenInclude(x => x.ProductImages).Where(x => x.AppUserId == user.Id).ToList());
            }
            else
            {
                var basketItemsStr = HttpContext.Request.Cookies["basketItemList"];

                if (basketItemsStr != null)
                {
                    List<CookieBasketItemDto> cookieItems = JsonConvert.DeserializeObject<List<CookieBasketItemDto>>(basketItemsStr);
                    basket = _getBasketItems(cookieItems);
                }
            }


            HeaderDto headerVM = new HeaderDto
            {
                Basket = basket
            };
            return View(headerVM);
        }

        private BasketDto _getBasketItems(List<CookieBasketItemDto> cookieBasketItems)
        {
            BasketDto basket = new BasketDto
            {
                BasketItems = new List<BasketItemDto>(),
            };

            foreach (var item in cookieBasketItems)
            {
                Product product = _context.Products.Include(x => x.ProductImages).Include(x => x.Brand).Include(x => x.ProductColors).ThenInclude(x => x.Color).FirstOrDefault(x => x.Id == item.ProductId);
                BasketItemDto basketItem = new BasketItemDto
                {
                    Brand = product.Brand.Name,
                    Model = product.Model,
                    Price = product.DiscountPercent > 0 ? (product.SalePrice * (1 - product.DiscountPercent / 100)) : product.SalePrice,
                    ProductId = product.Id,
                    Count = item.Count,
                    PosterImage = product.ProductImages.FirstOrDefault(x => x.PosterStatus == true)?.Image
                };

                basketItem.TotalPrice = basketItem.Count * basketItem.Price;
                basket.TotalAmount += basketItem.TotalPrice;
                basket.BasketItems.Add(basketItem);
            }

            return basket;
        }

        private BasketDto _getBasketItems(List<BasketItem> basketItems)
        {
            BasketDto basket = new BasketDto
            {
                BasketItems = new List<BasketItemDto>(),
            };

            foreach (var item in basketItems)
            {
                BasketItemDto basketItem = new BasketItemDto
                {
                    Brand = item.Product.Brand.Name,
                    Model = item.Product.Model,
                    Price = item.Product.DiscountPercent > 0 ? (item.Product.SalePrice * (1 - item.Product.DiscountPercent / 100)) : item.Product.SalePrice,
                    ProductId = item.Product.Id,
                    Count = item.Count,
                    PosterImage = item.Product.ProductImages.FirstOrDefault(x => x.PosterStatus == true)?.Image
                };

                basketItem.TotalPrice = basketItem.Count * basketItem.Price;
                basket.TotalAmount += basketItem.TotalPrice;
                basket.BasketItems.Add(basketItem);
            }

            return basket;
        }
    }
}

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/_CommentFormPartial.cshtml
@using BrandShop.Business.DTOs.CommentDto
@model CreateCommentDto

<div class="comments">

    <h2>Şərh yazın</h2>
   

    <form class="comments__form" asp-action="Comment" method="post" id="add-comment">
        <div class="d-flex justify-content-between align-items-center">
             <div class="rate">
                <input type="radio" id="star1" asp-for="Rate" value="5" />
                <label for="star1" title="text">5 stars</label>
                <input type="radio" id="star2" asp-for="Rate" value="4" />
                <label for="star2" title="text">4 stars</label>
                <input type="radio" id="star3" asp-for="Rate" value="3" />
                <label for="star3" title="text">3 stars</label>
                <input type="radio" id="star4" asp-for="Rate" value="2" />
                <label for="star4" title="text">2 stars</label>
                <input type="radio" id="star5" asp-for="Rate" value="1" />
                <label for="star5" title="text">1 star</label>
            </div>
            <span class="text-danger" asp-validation-for="Rate"></span>

            <div class="comments__form-text">
                <div class="comments__form-field">
                    <textarea id="comments__form-label-text"
                              placeholder="Fikirlərinizi ifadə edin" asp-for="Text"
                              class="comments__form-input comments__form-textarea"></textarea>
                    <label asp-for="Text" class="comments__form-label" for="comments__form-label-text">
                        <span class="comments__form-label-text">Fikirlərinizi ifadə edin</span>
                    </label>
                    <span class="text-danger" asp-validation-for="Text"></span>
                </div>
            </div>
         </div>

         <input type="hidden" asp-for="ProductId"/> 

        <button name="submit" type="submit" id="submit" class="comments__form-submit">Göndər</button>
    </form>

    <div class="comments__list">
        <!-- Comments -->
    </div>
</div>

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/_Layout.cshtml
@using BrandShop.Business.DTOs.ProductDto

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Title icon-->
    <link rel="shortcut icon" href="/assets/images/titleIcon.svg" type="image/x-icon">
    <!--Boxicons CDN-->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>

    <!--Owl carousel CSS-->
    <link rel="stylesheet" href="/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/assets/css/owl.theme.default.css">

    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <!--Toaster-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--Custom css-->
    <link rel="stylesheet" href="/assets/css/style.css">
    <link rel="stylesheet" href="/assets/css/plugins.css">

    <title>@ViewData["Title"]</title>
</head>

<body>
    <div class="loader">
        <div class="spinner-border" style="color: #F1A634 !important; width: 3rem; height: 3rem;" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    
    @await Component.InvokeAsync("Header")

    @RenderBody()
    @if (TempData["Error"] != null)
    {
        <input type="hidden" id="toaster-error" style="font-family: sans-serif;" value="@TempData["Error"]" />
    }
    @if (TempData["Success"] != null)
    {
        <input type="hidden" id="toaster-success" value="@TempData["Success"]" />
    }

    @await Component.InvokeAsync("Footer")

    <!--jQuery CDN-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    <!--Owl carousel JavaScript-->
    <script src="/assets/js/owl.carousel.min.js"></script>
    <script src="/assets/js/_trendingOwlCarousel.js"></script>
    <script src="/assets/js/_likeOwlCarousel.js"></script>
    <script src="/assets/js/_brandOwlCarousel.js"></script>
    <script src="/assets/js/_bestOwlCarousel.js"></script>
    <script src="/assets/js/_smartOwlCarousel.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-top-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        $(document).ready(function() {
            if ($("#toaster-error").length) {
                console.log($("#toaster-error"))
                toastr["error"]($("#toaster-error").val())
            }
            if ($("#toaster-success").length) {
                console.log($("#toaster-success"))
                toastr["success"]($("#toaster-success").val())
            }
        })
    </script>

    <script src="/assets/js/main.js"></script>
</body>

</html>

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/_MemberQuesitionPartial.cshtml
@using BrandShop.Business.DTOs.HomeDto
@model QuestionDto

<div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title d-flex align-items-center" id="staticBackdropLabel"><i class="fa-solid fa-message-question"></i>Sual</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form asp-action="Index" method="post">
                    <div class="modal-body">
                        <div class="row">
                            <input type="hidden" />
                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input asp-for="FullName" class="form-control" id="fullName" placeholder="John Doe">
                                    <label asp-for="FullName">Ad və soyad</label>
                                    <span asp-validation-for="FullName" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input asp-for="Email" class="form-control" id="eMail" placeholder="name@example.com">
                                    <label asp-for="Email">Email adres</label>
                                    <span asp-validation-for="Email" class="text-danger"></span>

                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-floating">
                                    <textarea asp-for="Text" class="form-control" placeholder="Sualınız" id="question"
                                        style="height: 100px"></textarea>
                                    <label asp-for="Text">Sualınız</label>
                                    <span asp-validation-for="Text" class="text-danger"></span>

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Bağla</button>
                        <button type="submit" class="btn" style="
                       color: #FFFFFF; background-color: #F1A634;">Göndər</button>
                    </div>

                </form>


            </div>
        </div>

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/_MemberUpdateFormPartial.cshtml
@using BrandShop.Business.DTOs.AuthenticateDto
@model UpdateDto


        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel"><i class="fas fa-user-edit"></i>Profil</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form asp-action="Profile" method="post">
                    <div class="modal-body">
                        <div class="row">
                            @if(@Model.EmailConfirmed == false){
                                <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="userName" asp-for="UserName" placeholder="John Doe">
                                    <label asp-for="UserName">İstifadəçi adı</label>
                                    <span asp-validation-for="UserName"></span>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="eMail" asp-for="Email" placeholder="name@example.com">
                                    <label asp-for="Email">Email adres</label>
                                    <span asp-validation-for="Email"></span>
                                </div>
                            </div>
                            }

                            @if(@Model.EmailConfirmed == true) {
                                <input type = "hidden" asp-for="UserName" />
                                <input type = "hidden" asp-for="Email" />
                            }
                            

                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="address" asp-for="Address" placeholder="Bakı şəhəri Nərimanov Rayonu Bina 4 Mənzil 5">
                                    <label asp-for="Address">Ünvan</label>
                                    <span asp-validation-for="Address"></span>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input class="form-control" id="phone" asp-for="PhoneNumber" placeholder="John Doe">
                                    <label asp-for="PhoneNumber">Telefon</label>
                                    <span asp-validation-for="PhoneNumber"></span>
                                </div>
                            </div>

                            <div asp-validation-summary="ModelOnly"></div>


                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Bağla</button>
                        <button type="submit" class="btn" style="
                       color: #FFFFFF; background-color: #F1A634;">Yadda saxla</button>
                    </div>

                </form>


            </div>
        </div>

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/_MemberUpdatePasswordPartial.cshtml
@using BrandShop.Business.DTOs.AuthenticateDto
@model UpdateDto

<div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel"><i class="fas fa-lock"></i>Şifrə</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form asp-action="Profile" method="post">
                    <div class="modal-body">
                        <div class="row">
                            <input type="hidden" asp-for="UserName" />
                            <input type="hidden" asp-for="Email" />
                            <input type="hidden" asp-for="Address" />
                            <input type="hidden" asp-for="PhoneNumber" />
                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input type="password" class="form-control" id="nowPassword" asp-for="CurrentPassword" placeholder="John Doe">
                                    <label asp-for="CurrentPassword">Hal-hazırdakı şifrə</label>
                                    <span asp-validation-for="CurrentPassword"></span>
                                </div>
                            </div>

                            <div class="col-lg-6 col-md-12">
                                <div class="form-floating mb-3">
                                    <input type="password" asp-for="Password" class="form-control" id="newPassword"
                                        placeholder="name@example.com">
                                    <label asp-for="Password">Yeni şifrə</label>
                                    <span asp-validation-for="Password"></span>
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-floating mb-3">
                                    <input type="password" asp-for="RepeatPassword" class="form-control" id="repeatPassword"
                                        placeholder="name@example.com">
                                    <label asp-for="RepeatPassword">Yeni şifrənin təkrarı</label>
                                    <span asp-validation-for="RepeatPassword"></span>
                                </div>
                            </div>

                            <div asp-validation-summary="ModelOnly"></div>




                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Bağla</button>
                        <button type="submit" class="btn" style="
                       color: #FFFFFF; background-color: #F1A634;">Yadda saxla</button>
                    </div>

                </form>


            </div>
        </div>

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/_OrderFormPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using BrandShop.Core.Entities
@using BrandShop.Business.DTOs.OrderDto
@model OrderDto

@inject UserManager<AppUser> userManager
@{
    AppUser user = userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name && x.IsAdmin == false);
}

@*@model Order*@

<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title d-flex align-items-center" id="staticBackdropLabel"><i class='bx bx-task'></i>Sifariş</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form asp-action="Checkout" method="post">
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-floating mb-3">
                            <input asp-for="FullName" class="form-control" id="fullName" placeholder="John Doe">
                            <label asp-for="FullName">Ad və soyad</label>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="form-floating mb-3">
                            <input asp-for="Email" class="form-control" id="eMail" placeholder="name@example.com">
                            <label asp-for="Email">Email adres</label>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="form-floating mb-3">
                            <input asp-for="Address" class="form-control" id="address" placeholder="name@example.com">
                            <label asp-for="Address">Ünvan</label>
                        </div>
                    </div>

               @*     <div class="col-lg-12">
                        <div class="form-floating mb-3">
                            <input asp-for="Phone" class="form-control" id="phone" placeholder="John Doe">
                            <label asp-for="Phone">Telefon</label>
                        </div>
                    </div>*@


                </div>
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <input type="hidden" asp-for="AppUserId" value="@user?.Id" />
                <input type="hidden" asp-for="FullName" value="@user?.FullName" />
                <input type="hidden" asp-for="Email" value="@user?.Email" />

            }

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Bağla</button>
                <button type="submit" class="btn" style="
                       color: #FFFFFF; background-color: #F1A634;">
                    Tamamla
                </button>
            </div>

        </form>


    </div>
</div>