BrandBakuMVC/BrandShopMVC/BrandShopMVC/Controllers/OrderController.cs
using BrandShop.Business.DTOs.OrderDto;
using BrandShop.Business.DTOs.ProductDto;
using BrandShop.Core.Entities;
using BrandShop.Data.DAL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BrandShopMVC.Controllers
{
    public class OrderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public OrderController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> CheckOut()
        {
            OrderDto orderDto = new OrderDto
            {
                OrderItems = await _getCheckoutItems(),
                Order = new Order()
            };
            return View(orderDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(OrderDto order)
        {


            AppUser user = _userManager.Users.FirstOrDefault(x => x.IsAdmin == false && x.UserName == User.Identity.Name);
            if (user == null)
            {
                return RedirectToAction("signin", "authenticate");
            }


            List<OrderItemDto> checkoutItems = await _getCheckoutItems();

            if (checkoutItems.Count == 0)
            {
                ModelState.AddModelError("", "There is not any selected product");
            }

            if (!ModelState.IsValid)
            {
                return View("Checkout", new OrderDto { OrderItems = checkoutItems });
            }

            var lastOrder = _context.Orders.OrderByDescending(x => x.Id).FirstOrDefault();
            //order.CreatedAt = DateTime.UtcNow.AddHours(4);
            order.Status = BrandShop.Core.Enums.OrderStatus.Pending;
            order.DeliveryStatus = BrandShop.Core.Enums.OrderDeliveryStatus.OnProcessing;
            order.OrderItems = new List<OrderItemDto>();
            //order.AppUserId = user.Id;
            foreach (var item in checkoutItems)
            {
                OrderItemDto orderItem = new OrderItemDto
                {
                    
                    ProductId = item.Product.Id,
                    CostPrice = item.Product.CostPrice,
                    Count = item.Count,
                    SalePrice = item.Product.SalePrice,
                    DiscountPercent = item.Product.DiscountPercent
                };
                order.TotalAmount += orderItem.DiscountPercent > 0
                ? orderItem.SalePrice * (1 - orderItem.DiscountPercent / 100) * orderItem.Count
                : orderItem.SalePrice * orderItem.Count;
                order.OrderItems.Add(orderItem);
            }

            _context.Orders.Add(lastOrder);
            _context.BasketItems.RemoveRange(_context.BasketItems.Where(x => x.AppUserId == user.Id));
            _context.SaveChanges();
            return RedirectToAction("profile", "account");
        }

        private async Task<List<OrderItemDto>> _getCheckoutItems()
        {
            List<OrderItemDto> checkoutItems = new List<OrderItemDto>();

            AppUser user = null;
            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }

            if (user != null && user.IsAdmin == false)
            {
                List<BasketItem> basketItems = _context.BasketItems.Include(x => x.Product).ThenInclude(x => x.ProductImages).Include(x => x.Product).ThenInclude(x => x.Brand).Where(x => x.AppUserId == user.Id).ToList();

                foreach (var item in basketItems)
                {
                    OrderItemDto checkoutItem = new OrderItemDto
                    {
                        Product = item.Product,
                        Count = item.Count
                    };
                    checkoutItems.Add(checkoutItem);
                }
            }
            else
            {
                string basketItemsStr = HttpContext.Request.Cookies["basketItemList"];
                if (basketItemsStr != null)
                {
                    List<CookieBasketItemDto> basketItems = JsonConvert.DeserializeObject<List<CookieBasketItemDto>>(basketItemsStr);

                    foreach (var item in basketItems)
                    {
                        OrderItemDto checkoutItem = new OrderItemDto
                        {
                            Product = _context.Products.Include(x => x.ProductImages).Include(x => x.Brand).FirstOrDefault(x => x.Id == item.ProductId),
                            Count = item.Count
                        };
                        checkoutItems.Add(checkoutItem);
                    }
                }
            }

            return checkoutItems;
        }
    }
}

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Controllers/ProductController.cs
using BrandShop.Business.DTOs.CommentDto;
using BrandShop.Business.DTOs.ProductDto;
using BrandShop.Business.DTOs.WishDto;
using BrandShop.Core.Entities;
using BrandShop.Data.DAL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BrandShopMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ProductController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Shop(int? categoryId, int? colorId, decimal? minPrice = null, decimal? maxPrice = null)
        {

            var products = _context.Products
                .Include(x => x.Category)
                .Include(x => x.Brand)
                .Include(x => x.ProductImages)
                .Include(x => x.ProductColors)
                .ThenInclude(x => x.Color)
                .Where(x => x.IsDeleted == false)
                .AsQueryable();

            if (categoryId != null)
            {
                products = products.Where(x => x.CategoryId == categoryId);
            }

            ViewBag.MinPrice = (int)products.Min(x => x.SalePrice);
            ViewBag.MaxPrice = (int)products.Max(x => x.SalePrice);

            if (colorId != null)
            {
                products = products.Where(x => x.ProductColors.Any(d => d.ColorId == colorId));
            }

            if (minPrice != null && maxPrice != null)
            {
                products = products.Where(x => x.SalePrice >= minPrice && x.SalePrice <= maxPrice);
            }


            ViewBag.SelectedMinPrice = minPrice ?? ViewBag.MinPrice;
            ViewBag.SelectedMaxPrice = maxPrice ?? ViewBag.MaxPrice;

            ShopDto shopDto = new ShopDto
            {
                CategoryId = categoryId,
                ColorId = colorId,
                Categories = _context.Categories.Where(x => x.IsDeleted == false).ToList(),
                Subcategories = _context.Subcategories.Where(x => x.IsDeleted == false).ToList(),
                Brands = _context.Brands.Where(x => x.IsDeleted == false).ToList(),
                Colors = _context.Colors.ToList(),
                Products = products
                .Include(x => x.ProductImages)
                .Include(x => x.Brand)
                .Include(x => x.ProductColors)
                .ThenInclude(x => x.Color).ToList(),
            };
            return View(shopDto);
        }

        public async Task<IActionResult> Detail(int id)
        {
            ViewBag.ProductId = id;
            Product product = await _context.Products
                .Include(x => x.ProductImages)
                .Include(x => x.Brand)
                .Include(x => x.ProductComments)
                .Include(x => x.ProductColors)
                .ThenInclude(x => x.Color)
                .Where(x => x.IsDeleted == false)
                .FirstOrDefaultAsync(x => x.Id == id);

            DetailDto detailDto = new DetailDto
            {
                Product = product,
                CommentDto = new CreateCommentDto(),
                RelatedProduct = _context.Products
                .Include(x => x.ProductImages)
                .Include(x => x.Brand)
                .Include(x => x.ProductColors)
                .ThenInclude(x => x.Color)
                .Where(x => x.IsDeleted == false)
                .ToList(),
            };

            detailDto.CommentDto.ProductId = product.Id;

            return View(detailDto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comment(CreateCommentDto commentDto)
        {
            //return Ok(commentDto);

            var product = await _context.Products
                .Include(x => x.ProductImages)
                .Include(x => x.Brand)
                .Include(x => x.ProductComments)
                .Include(x => x.ProductColors)
                .ThenInclude(x => x.Color)
                .Where(x => x.IsDeleted == false && x.Id == commentDto.ProductId)
                .FirstOrDefaultAsync();

            if (product == null) return NotFound();

            AppUser user = await _userManager.FindByNameAsync(User.Identity.Name);

            ProductComment comment = new ProductComment
            {
                Text = commentDto.Text,
                Rate = commentDto.Rate,
                Status = false,
                ProductId = commentDto.ProductId,
                AppUserId = user.Id
            };

            DetailDto detailDto = new DetailDto
            {
                Product = product,
                Comment = comment,
                RelatedProduct = _context.Products
                .Include(x => x.ProductImages)
                .Include(x => x.Brand)
                .Include(x => x.ProductColors)
                .ThenInclude(x => x.Color)
                .Where(x => x.IsDeleted == false)
                .ToList(),
            };

            if (!ModelState.IsValid)
            {
                TempData["error"] = "Comment model is not valid!";

                return View("Detail", detailDto);
            }

            if (!_context.Products.Any(x => x.Id == comment.ProductId))
            {
                TempData["error"] = "Selected Product not found";
                return View("Detail", detailDto);
            }

            _context.ProductComments.Add(comment);
            _context.SaveChanges();

            TempData["Success"] = "Comment added successfully";

            return RedirectToAction("detail", new { Id = comment.ProductId });
        }

        public async Task<IActionResult> AddWish(int id)
        {
            if (!_context.Products.Any(x => x.Id == id))
            {
                return RedirectToAction("error", "error");
            }
            WishDto wishData = null;
            AppUser user = null;
            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }

            if (user != null && user.IsAdmin == false)
            {

                WishItem wishItem = _context.WishItems.FirstOrDefault(x => x.AppUserId == user.Id && x.ProductId == id);

                if (wishItem == null)
                {
                    wishItem = new WishItem
                    {
                        AppUserId = user.Id,
                        ProductId = id,
                    };
                    _context.WishItems.Add(wishItem);
                }

                _context.SaveChanges();

                wishData = _getWishItems(_context.WishItems.Include(x => x.Product).ThenInclude(x => x.Brand).Where(x => x.AppUserId == user.Id).ToList());

            }
            else
            {
                List<CookieWishItemDto> wishItems = new List<CookieWishItemDto>();
                string existWishItem = HttpContext.Request.Cookies["wishItemList"];
                if (existWishItem != null)
                {
                    wishItems = JsonConvert.DeserializeObject<List<CookieWishItemDto>>(existWishItem);
                }
                CookieWishItemDto item = wishItems.FirstOrDefault(x => x.ProductId == id);
                if (item == null)
                {
                    item = new CookieWishItemDto
                    {
                        ProductId = id,
                    };
                    wishItems.Add(item);
                }

                var productIdStr = JsonConvert.SerializeObject(wishItems);
                HttpContext.Response.Cookies.Append("wishItemList", productIdStr);
                wishData = _getWishItems(wishItems);
            }
            TempData["Success"] = "Məhsul bəyəndiklərimə əlavə olundu.";

            return RedirectToAction("wishlist", "wish");
        }

        public async Task<IActionResult> DeleteWish(int id)
        {
            AppUser user = _userManager.Users.FirstOrDefault(x => x.UserName == User.Identity.Name && x.IsAdmin == false);
            if (!_context.Products.Any(x => x.Id == id))
            {
                return RedirectToAction("error", "error");
            }
            List<WishItemDto> wishItems = new List<WishItemDto>();
            if (user != null && !user.IsAdmin)
            {
                WishItem wishItem = _context.WishItems.FirstOrDefault(x => x.ProductId == id);
                if (wishItem == null)
                {
                    return RedirectToAction("error", "error");
                }

                _context.WishItems.Remove(wishItem);
                _context.SaveChanges();
            }
            else
            {
                string wish = HttpContext.Request.Cookies["wishItemList"];
                wishItems = JsonConvert.DeserializeObject<List<WishItemDto>>(wish);
                WishItemDto productWish = wishItems.FirstOrDefault(x => x.ProductId == id);
                if (productWish == null)
                {
                    return RedirectToAction("error", "error");
                }

                wishItems.Remove(productWish);

                HttpContext.Response.Cookies.Append("wishItemList", JsonConvert.SerializeObject(wishItems));
            }

            TempData["Error"] = "Məhsul bəyəndiklərimdən silindi.";
            return RedirectToAction("wishlist", "wish");

        }

        private WishDto _getWishItems(List<CookieWishItemDto> cookieWishItems)
        {

            WishDto wishItems = new WishDto()
            {
                WishItems = new List<WishItemDto>(),
            };
            foreach (var item in cookieWishItems)
            {
                Product product = _context.Products.Include(x => x.Brand).FirstOrDefault(x => x.Id == item.ProductId);

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Controllers/WishController.cs
using BrandShop.Business.DTOs.WishDto;
using BrandShop.Core.Entities;
using BrandShop.Data.DAL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BrandShopMVC.Controllers
{
    public class WishController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public WishController(AppDbContext context , UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> WishList()
        {
            WishListDto wishListVM = new WishListDto
            {
                WishListItems = await _getWishItems(),
            };
            return View(wishListVM);
        }

        private async Task<List<WishListItemDto>> _getWishItems()
        {
            List<WishListItemDto> wishlistItems = new List<WishListItemDto>();

            AppUser user = null;
            if (User.Identity.IsAuthenticated)
            {
                user = await _userManager.FindByNameAsync(User.Identity.Name);
            }

            if (user != null && user.IsAdmin == false)
            {
                List<WishItem> wishItems = _context.WishItems.Include(x => x.Product).ThenInclude(x => x.ProductImages).Include(d => d.Product).ThenInclude(d => d.Brand).Where(x => x.AppUserId == user.Id).ToList();

                foreach (var item in wishItems)
                {
                    WishListItemDto wishlistItem = new WishListItemDto
                    {
                        Product = item.Product,

                    };
                    wishlistItems.Add(wishlistItem);
                }
            }
            else
            {
                string wishItemsStr = HttpContext.Request.Cookies["wishItemList"];
                if (wishItemsStr != null)
                {
                    List<CookieWishItemDto> cookieWishItems = JsonConvert.DeserializeObject<List<CookieWishItemDto>>(wishItemsStr);

                    foreach (var item in cookieWishItems)
                    {
                        WishListItemDto checkoutItem = new WishListItemDto
                        {
                            Product = _context.Products.Include(x => x.ProductImages).Include(x => x.Brand).FirstOrDefault(x => x.Id == item.ProductId),

                        };
                        wishlistItems.Add(checkoutItem);
                    }
                }
            }

            return wishlistItems;
        }
    }
}

BrandBakuMVC/BrandShopMVC/BrandShopMVC/Views/Shared/Components/Header/Default.cshtml
@using BrandShop.Business.DTOs.HeaderDto
@{
    Layout = null;
}

@model HeaderDto

<header class="fixed-top">
        <nav class="navbar navbar-expand-lg">
            <div class="container p-0">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="/assets/images/brandBakuLogo2.svg" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center active" aria-current="page" asp-controller="Home" asp-action="Index">
                                <i class='bx bx-home-smile'></i>Ana səhifə
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" asp-controller="Product" asp-action="Shop">
                                <i class='bx bxl-shopify'></i>Alış-veriş
                            </a>
                        </li>

                        <li class="nav-item d-flex">
                            <a class="nav-link d-flex align-items-center position-relative p-0 m-0" asp-controller="Order"
                               asp-action="CheckOut">
                                <i class='bx bx-cart-alt'></i>
                                <span class="position-absolute top-0 start-100 translate-middle d-flex justify-content-center align-items-center rounded-circle" style="padding-left: 5px; padding-right: 5px; padding-top: 3px; padding-bottom: 3px; background-color: #F1A634; color: #FFFFFF;">
                                    <span class="visually" style="font-size: 13px;">@(Model.Basket?.BasketItems.Count()??0)</span>
                                </span>
                            </a>
                            <a class="nav-link d-flex align-items-center ps-0" asp-controller="Order" asp-action="CheckOut">
                                Səbət

                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center" asp-controller="Wish" asp-action="WishList">
                                <i class='bx bx-heart'></i>Bəyəndiklərim
                            </a>
                        </li>

                        <li class="nav-item account">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link d-flex align-items-center"><i class='bx bx-user'></i>@User.Identity.Name</a>

                                <ul>
                                    <li>
                                        <a asp-controller="Authenticate" asp-action="Profile">
                                            <i class='bx bx-user-circle'></i>Profil
                                        </a>
                                    </li>

                                    <li>
                                        <a asp-controller="Authenticate" asp-action="Logout">
                                            <i class='bx bx-log-out-circle'></i>Çıxış
                                        </a>
                                    </li>
                                </ul>
                            }

                            else
                            {
                                <a class="nav-link d-flex align-items-center" asp-controller="Authenticate" asp-action="SignIn"><i class='bx bx-user'></i>Hesab</a>
                            }

                        </li>
                    </ul>
                    <form class="search-form" role="search">
                        <input class="form-control me-2" type="search" placeholder="Axtar..." aria-label="Search">
                        <button class="btn" type="submit"><i class='bx bx-search-alt-2'></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>